version: '3.8'

services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    expose: 
      - 5432
    restart: unless-stopped

volumes:
  db: {}